# Generated by Django 4.1.4 on 2022-12-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionMetrica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dimension',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('peso', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='indicador',
            fields=[
                ('codigo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('peso', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
